import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blogs',
  description: 'Generated by PKM',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      {/* <head>

        <script>
          window.fbAsyncInit = function() {
            FB.init({
              appId: '{your-app-id}',
              cookie: true,
              xfbml: true,
              version: '{api-version}'
            });

          FB.AppEvents.logPageView();   
      
  };

          (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) {return;}
          js = d.createElement(s); js.id = id;
          js.src = "https://connect.facebook.net/en_US/sdk.js";
          fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
        </script>
      </head> */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
